apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: boardgame-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: boardgame-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: nginx_http_requests_total
      targetAverageValue: 10